In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import csv

In [2]:
train_data = pd.read_csv('/Users/dannyshau/.kaggle/competitions/introml2018p4/introML2018.task4.train.csv')

In [3]:
test_data = pd.read_csv('/Users/dannyshau/.kaggle/competitions/introml2018p4/introML2018.task4.test.csv')

In [4]:
sample_data = pd.read_csv('/Users/dannyshau/.kaggle/competitions/introml2018p4/sampleSubmission.csv')

In [5]:
train_data.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,label
0,1.17028,66.09730,72.46619,22.16377,-1.00000,1.05144,-1.00000,9.61007,5.89010,0.47940,...,3.89590,3.67345,-1.00000,8.32599,10.07659,3.63424,9.44136,6.80444,-1.00000,0
1,71.35278,-1.00000,57.94249,0.18357,44.77573,1.68090,13.67057,0.66133,3.83402,7.84703,...,1.47023,4.45295,1.10557,1.58882,3.18659,6.11452,8.08167,6.75342,4.26742,0
2,3.70219,25.13387,21.48021,45.59859,51.29388,1.36740,5.07522,12.24377,7.42950,1.07976,...,1.92691,3.76264,-1.00000,7.50615,6.48210,3.93660,10.73871,7.66258,5.18974,0
3,67.33205,13.61315,63.06888,71.99360,13.12082,1.15587,13.52942,7.60036,7.24176,1.61245,...,3.41919,1.73773,5.31040,6.44143,10.22145,-1.00000,0.67181,1.44988,5.36941,0
4,71.86121,48.46018,9.69637,56.40512,27.96404,-1.00000,6.47372,10.95237,8.95040,2.57170,...,0.27749,2.24290,4.29447,10.18216,7.11804,6.41332,5.33511,0.24253,5.45418,0

In [6]:
train_data.describe()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,label
count,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,...,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06,4.000000e+06
mean,2.329976e+01,2.328899e+01,2.329538e+01,2.329390e+01,2.329427e+01,4.510180e+00,4.738221e+00,4.518186e+00,4.344104e+00,4.508001e+00,...,4.454523e+00,4.480261e+00,4.434131e+00,4.375295e+00,4.530716e+00,4.436475e+00,4.541590e+00,4.533463e+00,4.659642e+00,2.000000e+00
std,2.213177e+01,2.210958e+01,2.212235e+01,2.213241e+01,2.212255e+01,4.570341e+00,4.734311e+00,4.613511e+00,4.481322e+00,4.592540e+00,...,4.518280e+00,4.566692e+00,4.535719e+00,4.508294e+00,4.568689e+00,4.564833e+00,4.606170e+00,4.579382e+00,1.704799e+00,1.414214e+00
min,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,...,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00
25%,5.076585e+00,5.091460e+00,5.078750e+00,5.074020e+00,5.081758e+00,8.838100e-01,9.327000e-01,8.504575e-01,8.417900e-01,8.204375e-01,...,8.607475e-01,8.478500e-01,8.600100e-01,8.162100e-01,9.213275e-01,8.216800e-01,9.004700e-01,9.201500e-01,4.210300e+00,1.000000e+00
50%,1.671772e+01,1.671697e+01,1.671802e+01,1.670476e+01,1.671282e+01,3.257500e+00,3.451075e+00,3.201040e+00,3.050810e+00,3.217610e+00,...,3.224400e+00,3.213385e+00,3.168685e+00,3.088990e+00,3.268715e+00,3.148210e+00,3.293470e+00,3.278720e+00,4.919450e+00,2.000000e+00
75%,3.641869e+01,3.638653e+01,3.642706e+01,3.641291e+01,3.641761e+01,7.185233e+00,7.630920e+00,7.278750e+00,6.905123e+00,7.298055e+00,...,7.123370e+00,7.172623e+00,7.028650e+00,7.005002e+00,7.244992e+00,7.071010e+00,7.203563e+00,7.190622e+00,5.605110e+00,3.000000e+00
max,9.899954e+01,9.899643e+01,9.899943e+01,9.899933e+01,9.899009e+01,3.795792e+01,3.357029e+01,3.504167e+01,3.157594e+01,3.162702e+01,...,3.452895e+01,3.306791e+01,3.459009e+01,3.117587e+01,3.672234e+01,3.223187e+01,3.407382e+01,3.528180e+01,1.091404e+01,4.000000e+00

In [7]:
sample_data.head()

   ID  label
0   1      1
1   2      4
2   3      3
3   4      3
4   5      3

In [8]:
x_data = train_data.drop('label', axis=1)
y_data = train_data['label']
print(x_data.shape)
print(y_data.shape)

(4000000, 26)
(4000000,)

In [9]:
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

/Users/DannyShau/anaconda/envs/py3.5/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

(3000000, 26)
(1000000, 26)
(3000000,)
(1000000,)

In [10]:
def classification(model):
    print(model)
    model.fit(x_train, y_train)
    print(model.score(x_train, y_train))
    y_model = model.predict(x_test)
    from sklearn.metrics import accuracy_score
    print(accuracy_score(y_test, y_model))
    return model

In [11]:
def predict(model):
    result = model.predict(test_data)
    file_name = 'result.csv'
    with open(file_name, 'w', newline='') as csvfile:
        fieldnames = ['ID', 'label']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for i, j in enumerate(result):
            writer.writerow({'ID': i+1, 'label': j})
    return result

In [12]:
from sklearn import tree
model = classification(tree.DecisionTreeClassifier())
result = predict(model)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
1.0
0.388773
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
(1000000,)

In [12]:
from sklearn.ensemble import RandomForestClassifier
model = classification(RandomForestClassifier(n_estimators=100))
result = predict(model)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
1.0
0.688963

In [13]:
from sklearn.neural_network import MLPClassifier
model = classification(MLPClassifier())
result = predict(model)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)
0.372608666667
0.372334